- hosts: all
  become: true
  roles:
    - role: commons

- hosts: routers
  become: true
  roles:
   - role: routers
   - role: dhcp

- hosts: cliente1
  become: true
  roles:
   - role: apache2

- hosts: clientes
  become: true
  roles:
   - role: clientes



